### PR TITLE
feat: add kaocha tests runner, run code coverage, bump deps, test multiple JDKs

### PR DESCRIPTION
**Pull request by k13gomez**
- Swap the tests runner to kaocha.
- Add test coverage using clovegage plugin for kaocha.
- Integrate coverage reporting with PRs via LCOV action.
- Bump several dependencies, I didn't see any problems having reviewed changelogs/release notes, but if you would like take a closer look.
- Bumping deps I noticed that some newer versions of deps fail with Jdk 8 due to being compiled with newer JDK 11, so I configured GH Actions to run with JDK 8 -> 22 via mise-en-place.

### CODE REVIEW

**Comment by cnuernber** [comment]
So I checked and we can't drop support for JDK-8 just yet for published/released jars. Clojure will drop support after 12 so then we could do that with our core dependencies -- looking through the changed deps it appears that only the various development profiles have been changed which I have no problem with.

I need to work with this for a bit and see if it fits my normal development pathways - there are multiple changes here I need to verify a bit.

**Comment by cnuernber** [comment]
It works on my mac - thanks for this work I think it modernizes the build process and the code coverage and library updates are definitely appreciated.

**Comment by k13gomez** [comment]
Great, I may have a follow up for this to turn the different JVM builds into a matrix job, it should be a bit nicer but not much change in practice so I will experiment with it later.

**Comment by cnuernber** [comment]
I was thinking the same thing but also figured it could wait - again thanks for this work!

**Pull request merged**
